version: '3.8'

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    env_file:
      - .env

  redis:
    restart: always
    image: redis:7.0.5-alpine
    hostname: redis
    ports:
      - 6379:6379
